students_account/urls.py
import settings
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('students_app.views',
    # Example:
    (r'^index/$', 'login'),
    (r'^logout/$', 'logout'),
    (r'^groups/$', 'view_groups'),
    (r'^groups/(?P<group_name>(\w*))$', 'view_students'),
    (r'^students/$', 'view_students'),
    (r'^edit/group/$', 'edit_group'),
    (r'^edit/student/$', 'edit_student'),
    (r'^jqgrid/(?P<grid_name>(\w+))/$', 'grid_handler', {}, 'grid_handler'),
    (r'^jqgrid/cfg/(?P<grid_name>(\w+))/$', 'grid_config', {}, 'grid_config'),
    # (r'^students_account/', include('students_account.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    #Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
    { 'document_root': settings.MEDIA_ROOT }),
)

students_account/students_app/models.py
from django.contrib.auth.models import User, UserManager
from django.db import models
from django.db.models.signals import post_save, post_delete

class MyLog(models.Model):
    model_name = models.CharField(max_length=32)
    inst = models.CharField(max_length=32)
    time = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=8)

    def __unicode__(self):
        return u'%s %s - %s %s' % (self.model_name, self.inst,
                                       self.time, self.action)

class Grup(models.Model):
    name = models.CharField(max_length=16, unique=True)
    student = models.ForeignKey('Student', related_name='student',
                                null=True, blank=True)

    def __unicode__(self):
        return self.name + u''


class Student(models.Model):
    surname = models.CharField(max_length=32)
    name = models.CharField(max_length=32)
    patronymic = models.CharField(max_length=32)
    birth_date = models.DateField()
    student_card = models.CharField(max_length=16)
    grup = models.ForeignKey(Grup, related_name='grup')

    def __unicode__(self):
        return u'%s %s' % (self.surname, self.name)

    class Meta:
        unique_together = [('surname', 'name', 'patronymic')]


def log_save(instance, created, **kwargs):
    act = created and 'create' or 'save'
    log_entry = MyLog(model_name=type(instance).__name__,
                    inst=unicode(instance)[:31], action=act)
    log_entry.save()

def log_delete(instance, **kwargs):
    log_entry = MyLog(model_name=type(instance).__name__,
                    inst=unicode(instance)[:31], action='delete')
    log_entry.save()

post_save.connect(log_save, sender=Grup, dispatch_uid="log_save_grup_uid")
post_save.connect(log_save, sender=Student, dispatch_uid="log_save_stud_uid")
post_delete.connect(log_delete, sender=Grup, dispatch_uid="log_del_grup_uid")
post_delete.connect(log_delete, sender=Student, dispatch_uid="log_del_stud_uid")

students_account/students_app/views.py
# Create your views here.
import logging
import students_app.grids
from django.contrib import auth
from django.forms.util import ValidationError
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.db.models import Count
from django.shortcuts import render_to_response
from django.template import RequestContext
from students_app.context_processors import settings_proc
from students_app.models import Grup, Student
from students_app.utils.main_utils import is_authenticated, class_for_name

DEFAULT_START_PAGE = '../groups'
ERROR_MESSAGE = "Please enter a correct username and password"


def login(request):
    if not request.POST:
        return display_login_form(request)
    if not request.session.test_cookie_worked():
        message = """Looks like your browser isn't configured to accept cookies.
                  Please enable cookies, reload this page, and try again."""
        return display_login_form(request, message)
    else:
        request.session.delete_test_cookie()
    username = request.POST['username']
    password = request.POST['password']
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        auth.login(request, user)
        return HttpResponseRedirect(DEFAULT_START_PAGE)
    else:
        return display_login_form(request, ERROR_MESSAGE)


def logout(request):
    request.session.flush()
    return HttpResponseRedirect('../index')

def display_login_form(request, error_message='', extra_context=None):
    request.session.set_test_cookie()
    context = {
               'title': 'Log in',
               'app_path': request.get_full_path(),
               'error_message': error_message,
               'is_login_page':True
               }
    context.update(extra_context or {})
    context_instance = RequestContext(request, current_app='students_app')
    return render_to_response('login.html', context,
                              context_instance=context_instance)


@is_authenticated
def view_groups(request):
    groups = Grup.objects.all().annotate(students_amount=Count('student'))
    return render_to_response('groups.html', {'groups':groups},
                              context_instance=RequestContext(request))


@is_authenticated
def view_students(request, group_name):
    students = Student.objects.all()
    return render_to_response('students.html', {'students':students},
                              context_instance=RequestContext(request))

@is_authenticated
def edit_group(request):
    """modifies or deletes Grup instance"""
    if request.method == 'POST' and request.POST:
        logging.debug(request.POST)
        if request.POST.get('oper') and request.POST['oper'] == 'del':
            try:
                Grup.objects.get(id=request.POST['id']).delete()
            except Exception, ex:
                logging.debug(ex)
        elif request.POST.get('oper') and request.POST['oper'] == 'add':
            instance = Grup()
            instance.name = request.POST.get('name')
            instance.student = Student.objects.get(id=request.POST.get('student'))
            try:
                instance.save()
            except Exception, ex:
                logging.debug(ex)
        else:
            try:
                instance = Grup.objects.get(id=request.POST.get('id'))
                instance.name = request.POST.get('name')
                instance.student = Student.objects.get(id=request.POST.get('student'))
                instance.save()
            except Exception, ex:
                logging.debug(ex)
        return render_to_response('grid-groups.html',
                                  context_instance=RequestContext(request))
    return HttpResponseNotFound('invalid request')


@is_authenticated
def edit_student(request):
    """modifies or deletes Student instance"""
    if request.method == 'POST' and request.POST:
        logging.debug(request.POST)
        instance = None
        if request.POST.get('oper') and request.POST['oper'] == 'del':
            try:
                Student.objects.get(id=request.POST['id']).delete()
            except Exception, ex:
                logging.debug(ex)
        elif request.POST.get('oper') and request.POST['oper'] == 'add':
            instance = Student()
        else:
            try:
                instance = Student.objects.get(id=request.POST.get('id'))
            except Exception, ex:
                logging.debug(ex)
        try:
            instance.surname = request.POST.get('surname')
            instance.name = request.POST.get('name')
            instance.patronymic = request.POST.get('patronymic')
            instance.birth_date = request.POST.get('birth_date')
            instance.student_card = request.POST.get('student_card')
            instance.grup = Grup.objects.get(id=request.POST.get('grup'))
            instance.save()
        except Exception, ex:
            logging.debug(ex)

        return render_to_response('grid-students.html',
                                  context_instance=RequestContext(request))
    return HttpResponseNotFound('invalid request')


def grid_handler(request, grid_name):
    """ handles pagination, sorting and searching"""
    logging.debug('grid handler %s' % grid_name)
    grid = class_for_name(grid_name, 'students_app.grids')()
    return HttpResponse(grid.get_json(request), mimetype="application/json")

def grid_config(request, grid_name):
    """build a config suitable to pass to jqgrid constructor"""
    logging.debug('grid config %s' % grid_name)
    grid = class_for_name(grid_name, 'students_app.grids')()
    return HttpResponse(grid.get_config(), mimetype="application/json")

students_account/templates/base.html
<html>
<head>
	{% block extrastyles %}{% endblock %}
	<!--  jquery custom  UI-->
	<link type="text/css" href="../site_media/css/custom-theme/jquery-ui-1.7.2.custom.css" rel="stylesheet"/>	
	<!-- jqGrid-->
	<link rel="stylesheet" type="text/css" media="screen" href="../site_media/css/jqGridGitHub/ui.jqgrid.css"/>
	<link rel="stylesheet" type="text/css" media="screen" href="../site_media/css/jqGridGitHub/jquery.searchFilter.css"/>
	
	<link rel="stylesheet" type="text/css" href="../site_media/css/main.css"/>
	
	<!--  jquery custom  UI-->
	<script type="text/javascript" src="../site_media/js/jqGridGitHub/jquery.js"></script>	
	<script type="text/javascript" src="../site_media/js/jquery-ui-1.7.2.custom.min.js"></script>	
	<script type="text/javascript" src="../site_media/js/jqGridGitHub/jquery.jqGrid.js"></script> 	
	<script type="text/javascript" src="../site_media/js/ui.datepicker-uk.js"></script>		
	{% block extrascripts %}{% endblock %}
</head>
<body>
	{%if not is_login_page %}
		you are logged in as <b>{{user.username}}</b> | <a href="../logout/">log out</a> 
	{% endif %}
	{% block content%}{% endblock %}
	{% if django_settings.DEBUG %}
		<hr /><b>debug: </b>
	{% endif %}
</body>
</html>

students_account/templates/grid-groups.html
{% block extrascripts %}
	{{ block.super }}
	<script type="text/javascript">
	$(document).ready(function () {
		$.getJSON("../jqgrid/cfg/"+"GrupGrid/", function(data){
			grid_config();
    	});
	});	
	grid_config = function(){
		$.getJSON("../jqgrid/cfg/"+"GrupGrid/", function(data){
			data['onSelectRow'] = on_select_row;
    	    $("#group_grid")
        	    .jqGrid(data)
            	.navGrid('#pager', 
                	{add: true, edit: true, del: true, view: false},
        	{closeOnEscape:true}, // edit options
        	{}, // add options
        	{}, // del options 
        	{ multipleSearch:true, closeOnEscape:true }, // search options 
        	{ jqModal:false, closeOnEscape:true} // view options 
        	);
    	});
	}
	var lastsel;
	on_select_row = function(id){
		if(id && id!==lastsel){
			jQuery('#group_grid').jqGrid('restoreRow', lastsel);
			jQuery('#group_grid').jqGrid('editRow',id, true);
			lastsel=id;
		}
	};
	$(document).keypress(function(e) {
		if(e.keyCode == 27) { 
			jQuery('#group_grid').jqGrid('restoreRow', lastsel);
		}
	});
	</script>
{% endblock %}

{% block content %}
	<table id="group_grid" class="scroll"></table>
	<div id="pager" class="scroll"></div>
{% endblock %}

students_account/templates/grid-students.html
{% block extrascripts %}
	{{ block.super }}
	<script type="text/javascript">
	$(document).ready(function () {
		$.getJSON("../jqgrid/cfg/"+"StudentGrid/", function(data){
			grid_config();
    	});
	});	
	grid_config = function(){
		$.getJSON("../jqgrid/cfg/"+"StudentGrid/", function(data){
			data['onSelectRow'] = on_select_row;
    	    $("#student_grid")
        	    .jqGrid(data)
            	.navGrid('#pager', 
                	{add: true, edit: true, del: true, view: false},
        	{closeOnEscape:true}, // edit options
        	{}, // add options
        	{}, // del options 
        	{ multipleSearch:true, closeOnEscape:true }, // search options 
        	{ jqModal:false, closeOnEscape:true} // view options 
        	);
    	});
	}
	var lastsel;
	on_select_row = function(id){
		if(id && id!==lastsel){
			jQuery('#student_grid').jqGrid('restoreRow', lastsel);
			jQuery('#student_grid').jqGrid('editRow',id, true, pickdates);
			lastsel=id;
		}
	};
	$(document).keypress(function(e) {
		if(e.keyCode == 27) { 
			jQuery('#student_grid').jqGrid('restoreRow', lastsel);
		}
	});
	function pickdates(id){
		jQuery("#"+id+"_birth_date","#student_grid").datepicker();
	}
	</script>
{% endblock %}

{% block content %}
	<table id="student_grid" class="scroll"></table>
	<div id="pager" class="scroll"></div>
{% endblock %}

students_account/templates/groups.html
{% extends 'base.html' %}
{% load students_tags %}

{% block extrascripts %}
	<script>
		function show_students(group) {
			window.location = "/students/"+ group;
		};
	</script>
{% endblock %}

{% block content%}
	{% include 'grid-groups.html' %}

	{% edit_list groups.1 students_app %}<br />
	{% edit_list request.user auth %}<br />
	{% edit_list groups.1.student students_app %}
{% endblock %}

students_account/templates/login.html
{% extends "base.html" %}

{% block content %}
  {% if error_message %}
    <p class="error">{{ error_message }}</p>
  {% endif %}

  <form action={{ app_path }} method="post">
	<table>
	<tr>
		<td><label for="username">Login or e-mail:</label></td>
		<td><input type="text" name="username" value="" id="username"></td>		
	</tr>
	<tr>
		<td><label for="password">Password:</label></td>
		<td><input type="password" name="password" value="" id="password"></td>		
	</tr>	
	</table>	
	<input type="submit" value="login" />
  </form>
{% endblock %}

students_account/templates/students.html
{% extends 'base.html' %}

{% block extrascripts %}
	<script>
		$(document).ready(function() {
			$('#id_birth_date').datepicker({dateFormat: 'yy-mm-dd', autoSize: true});
		});
	</script>
{% endblock %}

{% block content%}
	{% include 'grid-students.html' %}
{% endblock %}